# -*- coding: utf-8 -*-
"""RUS_OLIST_CHURN_V4.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P-7nMDfGk2LDeovcO7_sQjGsMtamnlLh
"""

!pip install pyspark -q

import json
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import userdata
from pyspark.sql import SparkSession
from functools import reduce
import pyspark.sql.functions as F
from pyspark.sql.functions import regexp_replace, lower, trim, length, concat_ws, col, when, count, isnan, sum, lit, desc
from pyspark.sql.functions import sum as spark_sum
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DoubleType, TimestampType, FloatType
import numpy as np
from pyspark.sql.window import Window

from imblearn.under_sampling import RandomUnderSampler

import kagglehub
import os

# Download dataset
dataset_path = kagglehub.dataset_download(
    "olistbr/brazilian-ecommerce"
)

print("Dataset path:", dataset_path)

# Membangun sesi Spark
spark = SparkSession.builder \
    .appName("Olist_EDA_BigData") \
    .master("local[*]") \
    .config("spark.driver.memory", "8g") \
    .config("spark.executor.memory", "8g") \
    .config("spark.sql.shuffle.partitions", "4") \
    .getOrCreate()

print("Spark Aktif. Versi:", spark.version)

"""# Bronze Layer

## Ingestion
"""

# --- SKEMA TABEL ORDERS ---
orders_schema = StructType([
    StructField("order_id", StringType(), True),
    StructField("customer_id", StringType(), True),
    StructField("order_status", StringType(), True),
    StructField("order_purchase_timestamp", TimestampType(), True),
    StructField("order_approved_at", TimestampType(), True),
    StructField("order_delivered_carrier_date", TimestampType(), True),
    StructField("order_delivered_customer_date", TimestampType(), True),
    StructField("order_estimated_delivery_date", TimestampType(), True)
])

# --- SKEMA TABEL ITEMS ---
items_schema = StructType([
    StructField("order_id", StringType(), True),
    StructField("order_item_id", IntegerType(), True),
    StructField("product_id", StringType(), True),
    StructField("seller_id", StringType(), True),
    StructField("shipping_limit_date", TimestampType(), True),
    StructField("price", DoubleType(), True),
    StructField("freight_value", DoubleType(), True)
])

# --- SKEMA TABEL PRODUCTS ---
products_schema = StructType([
    StructField("product_id", StringType(), True),
    StructField("product_category_name", StringType(), True),
    StructField("product_name_lenght", IntegerType(), True),
    StructField("product_description_lenght", IntegerType(), True),
    StructField("product_photos_qty", IntegerType(), True),
    StructField("product_weight_g", IntegerType(), True),
    StructField("product_length_cm", IntegerType(), True),
    StructField("product_height_cm", IntegerType(), True),
    StructField("product_width_cm", IntegerType(), True)
])

# --- SKEMA TABEL CUSTOMERS ---
customers_schema = StructType([
    StructField("customer_id", StringType(), True),
    StructField("customer_unique_id", StringType(), True),
    StructField("customer_zip_code_prefix", StringType(), True),
    StructField("customer_city", StringType(), True),
    StructField("customer_state", StringType(), True)
])

# --- SKEMA TABEL GEOLOCATION ---
geo_schema = StructType([
    StructField("geolocation_zip_code_prefix", StringType(), True),
    StructField("geolocation_lat", DoubleType(), True),
    StructField("geolocation_lng", DoubleType(), True),
    StructField("geolocation_city", StringType(), True),
    StructField("geolocation_state", StringType(), True)
])

# --- SKEMA TABEL PAYMENTS ---
payments_schema = StructType([
    StructField("order_id", StringType(), True),
    StructField("payment_sequential", IntegerType(), True),
    StructField("payment_type", StringType(), True),
    StructField("payment_installments", IntegerType(), True),
    StructField("payment_value", DoubleType(), True)
])

# --- SKEMA TABEL REVIEWS ---
reviews_schema = StructType([
    StructField("review_id", StringType(), True),
    StructField("order_id", StringType(), True),
    StructField("review_score", IntegerType(), True),
    StructField("review_comment_title", StringType(), True),
    StructField("review_comment_message", StringType(), True),
    StructField("review_creation_date", TimestampType(), True),
    StructField("review_answer_timestamp", TimestampType(), True)
])

# --- SKEMA TABEL SELLERS ---
sellers_schema = StructType([
    StructField("seller_id", StringType(), True),
    StructField("seller_zip_code_prefix", StringType(), True),
    StructField("seller_city", StringType(), True),
    StructField("seller_state", StringType(), True)
])

# --- SKEMA TABEL PRODUCT CATEGORY TRANSLATION ---
product_category_translation_schema = StructType([
    StructField("product_category_name", StringType(), True),
    StructField("product_category_name_english", StringType(), True)
])

def load_csv(filename, schema, **kwargs):
    return spark.read.csv(
        os.path.join(dataset_path, filename),
        header=True,
        schema=schema,
        **kwargs
    )

orders = load_csv(
    "olist_orders_dataset.csv",
    orders_schema
)

items = load_csv(
    "olist_order_items_dataset.csv",
    items_schema
)

products = load_csv(
    "olist_products_dataset.csv",
    products_schema
)

customers = load_csv(
    "olist_customers_dataset.csv",
    customers_schema
)

geo = load_csv(
    "olist_geolocation_dataset.csv",
    geo_schema
)

payments = load_csv(
    "olist_order_payments_dataset.csv",
    payments_schema
)

reviews = load_csv(
    "olist_order_reviews_dataset.csv",
    reviews_schema,
    multiLine=True,
    escape='"'
)

sellers = load_csv(
    "olist_sellers_dataset.csv",
    sellers_schema
)

product_category_translation = load_csv(
    "product_category_name_translation.csv",
    product_category_translation_schema
)

table_dict = {
    "orders": orders,
    "items": items,
    "products": products,
    "customers": customers,
    "geo": geo,
    "payments": payments,
    "reviews": reviews,
    "sellers": sellers,
    "product_category_translation": product_category_translation
}

for name, df in table_dict.items():
  print(f"table {name}:")
  df.sample(withReplacement=False, fraction=0.1).limit(5).show()

# 1. Cek Volume Data
print("--- VOLUME DATA ---")
print(f"Total Baris Orders     : {orders.count():,}")
print(f"Total Baris Items      : {items.count():,}")
print(f"Total Baris Products   : {products.count():,}")
print(f"Total Baris Customers  : {customers.count():,}")
print(f"Total Baris Geolocation: {geo.count():,}")
print(f"Total Baris Payments   : {payments.count():,}")
print(f"Total Baris Reviews    : {reviews.count():,}")
print(f"Total Baris Sellers    : {sellers.count():,}")
print(f"Total Baris Product Category Translation: {product_category_translation.count():,}")
print("\n")

# 2. Cek Skema
print("--- SKEMA TABEL ORDERS ---")
orders.printSchema()

print("--- SKEMA TABEL ITEMS ---")
items.printSchema()

print("--- SKEMA TABEL PRODUCTS ---")
products.printSchema()

print("--- SKEMA TABEL CUSTOMERS ---")
customers.printSchema()

print("--- SKEMA TABEL GEOLOCATION ---")
geo.printSchema()

print("--- SKEMA TABEL PAYMENTS ---")
payments.printSchema()

print("--- SKEMA TABEL REVIEWS ---")
reviews.printSchema()

print("--- SKEMA TABEL SELLERS ---")
sellers.printSchema()

print("--- SKEMA TABEL PRODUCT CATEGORY TRANSLATION ---")
product_category_translation.printSchema()

"""# Silver Layer

## Order Dataset EDA
"""

orders.show(5, truncate=False)

import pyspark.sql.functions as F

# Ambil tanggal transaksi pertama dan terakhir secara presisi
orders.agg(
    F.min("order_purchase_timestamp").alias("Transaksi_Pertama"),
    F.max("order_purchase_timestamp").alias("Transaksi_Terakhir")
).show(truncate=False)

# Cek Null Values Table Orders

orders.select([
    count(when(
        col(c).isNull() |
        (isnan(col(c)) if isinstance(orders.schema[c].dataType, (DoubleType, FloatType)) else False),
        c
    )).alias(c)
    for c in orders.columns
]).show()

# Cek Duplicate Values Table Orders

orders.groupBy("order_id").count().filter(F.col("count") > 1).show()

# Cek Total Order Status yang tidak ada null nya
orders.dropna().groupBy('order_status').count().orderBy(F.desc('count')).show()

# Build a list of conditions for null or NaN for each column
conditions = []
for c in orders.columns:
    is_null_cond = col(c).isNull()
    if isinstance(orders.schema[c].dataType, (DoubleType, FloatType)):
        conditions.append(is_null_cond | isnan(col(c)))
    else:
        conditions.append(is_null_cond)

# Combine all conditions with OR to find rows with any null/NaN
if conditions:
    any_null_row_condition = reduce(lambda a, b: a | b, conditions)
else:
    any_null_row_condition = F.lit(False)

# Filter the DataFrame to get rows with any null/NaN
df_with_nulls = orders.filter(any_null_row_condition)

# Count value_counts for 'order_status' in the filtered DataFrame
df_with_nulls.groupBy('order_status').count().orderBy(F.desc('count')).show()

"""### Membuat Fitur Baru"""

# purchased_approved = Jam yang dibutuhkan bagi pesanan untuk disetujui dari waktu pembelian
orders = orders.withColumn(
    'purchased_approved',
    (F.unix_timestamp(F.col("order_approved_at")) - F.unix_timestamp(F.col("order_purchase_timestamp"))) / 3600
)

# approved_carrier = Hari yang dibutuhkan bagi pesanan untuk dikirim ke kurir dari waktu penyetujuan pesanan
orders = orders.withColumn(
    'approved_carrier',
    F.datediff(F.col("order_delivered_carrier_date"), F.col("order_approved_at"))
)

# carrier_delivered = Hari yang dibutuhkan bagi pesanan untuk sampai kepada pembeli dari waktu awal dikirim
orders = orders.withColumn(
    'carrier_delivered',
    F.datediff(F.col("order_delivered_customer_date"), F.col("order_delivered_carrier_date"))
)

# delivered_estimated = Perbedaan hari dari tanggal estimasi dan tanggal pesanan sampai
orders = orders.withColumn(
    'delivered_estimated',
    F.datediff(F.col("order_estimated_delivery_date"), F.col("order_delivered_customer_date"))
)

# purchased_delivered = Hari yang dibutuhkan dari pembeli memesan hingga pesanan tiba
orders = orders.withColumn(
    'purchased_delivered',
    F.datediff(F.col("order_delivered_customer_date"), F.col("order_purchase_timestamp"))
)

orders.show(5)

orders.describe().show()
# Count = Jumlah data
# Mean = Rata - Rata
# Stddev = Standar deviasi untuk melihat pesebaran data
# Min = Nilai minimum
# Max = Nilai maximum

# Filter out rows where approved_carrier is negative (allowing nulls for canceled orders)
orders = orders.filter((F.col("approved_carrier") >= 0) | F.col("approved_carrier").isNull())

# Filter out rows where carrier_delivered is negative (allowing nulls for canceled orders)
orders = orders.filter((F.col("carrier_delivered") >= 0) | F.col("carrier_delivered").isNull())

# Filter order status: only delivered and canceled
orders = orders.filter(F.col("order_status").isin("delivered", "canceled"))

orders.describe().show()

# 1. Filter out rows that have any nulls AND are not 'delivered' or 'canceled'
# We want to keep rows where (no nulls) OR (has nulls AND order_status IN ('delivered', 'canceled'))
conditions = []
for c in orders.columns:
    is_null_cond = col(c).isNull()
    if isinstance(orders.schema[c].dataType, (DoubleType, FloatType)):
        conditions.append(is_null_cond | isnan(col(c)))
    else:
        conditions.append(is_null_cond)

# Combine all conditions with OR to find rows with any null/NaN
any_null_row_condition = reduce(lambda a, b: a | b, conditions) if conditions else F.lit(False)

orders = orders.filter((~any_null_row_condition) | (F.col('order_status').isin('delivered', 'canceled')))

# 2. Impute nulls in 'order_approved_at' using median 'purchased_approved' duration (in seconds, so we multiply by 3600 since median_purchased_approved is in hours)
median_purchased_approved = orders.agg(F.expr("percentile_approx(purchased_approved, 0.5)")).collect()[0][0]
orders = orders.withColumn(
    'order_approved_at',
    F.when(
        F.col('order_approved_at').isNull(),
        F.from_unixtime(F.unix_timestamp(F.col('order_purchase_timestamp')) + F.lit(median_purchased_approved * 3600))
    ).otherwise(F.col('order_approved_at'))
)

# 3. Impute nulls in 'order_delivered_carrier_date' using median 'approved_carrier' duration
median_approved_carrier = orders.agg(F.expr("percentile_approx(approved_carrier, 0.5)")).collect()[0][0]
orders = orders.withColumn(
    'order_delivered_carrier_date',
    F.when(
        F.col('order_delivered_carrier_date').isNull(),
        F.date_add(F.col('order_approved_at'), F.lit(median_approved_carrier))
    ).otherwise(F.col('order_delivered_carrier_date'))
)

# 4. Impute nulls in 'order_delivered_customer_date' using median 'carrier_delivered' duration
median_carrier_delivered = orders.agg(F.expr("percentile_approx(carrier_delivered, 0.5)")).collect()[0][0]
orders = orders.withColumn(
    'order_delivered_customer_date',
    F.when(
        F.col('order_delivered_customer_date').isNull(),
        F.date_add(F.col('order_delivered_carrier_date'), F.lit(median_carrier_delivered))
    ).otherwise(F.col('order_delivered_customer_date'))
)

# Recalculate derived columns after imputation to avoid carrying forward old NULL values
orders = orders.withColumn(
    'purchased_approved',
    (F.unix_timestamp(F.col("order_approved_at")) - F.unix_timestamp(F.col("order_purchase_timestamp"))) / 3600
)
orders = orders.withColumn(
    'approved_carrier',
    F.datediff(F.col("order_delivered_carrier_date"), F.col("order_approved_at"))
)
orders = orders.withColumn(
    'carrier_delivered',
    F.datediff(F.col("order_delivered_customer_date"), F.col("order_delivered_carrier_date"))
)
orders = orders.withColumn(
    'delivered_estimated',
    F.datediff(F.col("order_estimated_delivery_date"), F.col("order_delivered_customer_date"))
)
orders = orders.withColumn(
    'purchased_delivered',
    F.datediff(F.col("order_delivered_customer_date"), F.col("order_purchase_timestamp"))
)

# Cek Total Order Status
orders.groupBy('order_status').count().orderBy(F.desc('count')).show()

orders.describe().show()

# Cek Null Values Table Orders

orders.select([
    count(when(
        col(c).isNull() |
        (isnan(col(c)) if isinstance(orders.schema[c].dataType, (DoubleType, FloatType)) else False),
        c
    )).alias(c)
    for c in orders.columns
]).show()

"""## Customers EDA"""

customers.show(5, truncate=False)

# Cek Null Values

customers.select([
    count(when(
        col(c).isNull() |
        (isnan(col(c)) if isinstance(customers.schema[c].dataType, (DoubleType, FloatType)) else False),
        c
    )).alias(c)
    for c in customers.columns
]).show()

customers.describe().show()

# 1. Fungsi Pembersihan Teks (Modular)
def clean_city_name(df, column_name):
    # Daftar karakter beraksen bahasa Portugis/Brazil
    accents    = "áàâãäåéèêëíìîïóòôõöúùûüçñºª"
    # Huruf penggantinya (tanpa aksen)
    no_accents = "aaaaaaeeeeiiiiooooouuuucnoa"

    return df.withColumn(column_name, F.lower(F.col(column_name))) \
             .withColumn(column_name, F.translate(F.col(column_name), accents, no_accents)) \
             .withColumn(column_name, F.regexp_replace(F.col(column_name), "[^a-z0-9 ]", "")) \
             .withColumn(column_name, F.regexp_replace(F.col(column_name), " +", " ")) \
             .withColumn(column_name, F.trim(F.col(column_name)))

# 2. Eksekusi ke tabel Geolocation dan Customers
geo_clean = clean_city_name(geo, "geolocation_city")
customers_clean = clean_city_name(customers, "customer_city")

print("--- HASIL CLEANSING KOTA (BEFORE) ---")
geo.groupBy("geolocation_city") \
   .count() \
   .withColumnRenamed("geolocation_city", "geolocation_city (Sebelum Dibersihkan)") \
   .withColumnRenamed("count", "Total Baris") \
   .orderBy("geolocation_city (Sebelum Dibersihkan)") \
   .show(20, truncate=False)

print("\n--- HASIL CLEANSING KOTA (AFTER) ---")
geo_clean.groupBy("geolocation_city") \
         .count() \
         .withColumnRenamed("geolocation_city", "geolocation_city (Setelah Dibersihkan)") \
         .withColumnRenamed("count", "Total Baris") \
         .orderBy("geolocation_city (Setelah Dibersihkan)") \
         .show(20, truncate=False)

# Calculate value counts for customer_city
city_counts = customers_clean.groupBy("customer_city").count()

# Calculate total number of customers to get percentages
total_customers = customers_clean.count()

# Calculate percentage, order by percentage, and take the top 10
customerCity = city_counts.withColumn(
    "percentage", (col("count") / total_customers) * 100
).orderBy(col("percentage").desc()).limit(10)

print('The top 10 cities from which customers come are: \n')
customerCity.show(truncate=False)

plt.figure(figsize=(10, 5))
pdf_customerCity = customerCity.toPandas()
sns.barplot(y = pdf_customerCity['customer_city'], x = pdf_customerCity['count'], palette='viridis', hue=pdf_customerCity['customer_city'])
plt.xlabel('Number of Customers',color='black',fontsize=15)
plt.ylabel('Cities',color='black',fontsize=15)
plt.title('10 kota teratas pelanggan',color='black')
plt.show()

# Calculate value counts for customer_state
state_counts = customers_clean.groupBy("customer_state").count()

# Calculate total number of customers to get percentages
total_customers = customers_clean.count()

# Calculate percentage, order by percentage, and take the top 10
customerState = state_counts.withColumn(
    "percentage", (col("count") / total_customers) * 100
).orderBy(col("percentage").desc()).limit(10)

print('The top 10 states from which customers come are: \n')
customerState.show(truncate=False)

plt.figure(figsize=(10, 5))
pdf_customerState = customerState.toPandas()
sns.barplot(y = pdf_customerState['customer_state'], x = pdf_customerState['count'], palette='viridis', hue=pdf_customerState['customer_state'])
plt.xlabel('Number of Customers',color='black',fontsize=15)
plt.ylabel('States',color='black',fontsize=15)
plt.title('10 negara bagian teratas pelanggan',color='black')
plt.show()

# Filter the 'geo' DataFrame to include only coordinates within Brazil's approximate boundaries.
# Brazil's approximate latitude range: -33.75 to 5.27
# Brazil's approximate longitude range: -73.98 to -34.79
geo_clean = geo_clean.filter(
    (col("geolocation_lat") >= -33.75) & (col("geolocation_lat") <= 5.27) &
    (col("geolocation_lng") >= -73.98) & (col("geolocation_lng") <= -34.79)
)

geolocationMean = geo_clean.groupBy('geolocation_zip_code_prefix').agg(
    F.avg('geolocation_lat').alias('geolocation_lat'),
    F.avg('geolocation_lng').alias('geolocation_lng')
    )
geolocationMean.show()

customerDensity = customers_clean.join(geolocationMean, on=customers_clean['customer_zip_code_prefix'] == geolocationMean['geolocation_zip_code_prefix'], how = 'left').select('customer_unique_id', 'customer_zip_code_prefix', geolocationMean['geolocation_lat'], geolocationMean['geolocation_lng'])
customerDensity.show()

customerDensity = customerDensity.dropna()

import folium

# Sample the data to a manageable size for plotting (e.g., 10,000 points)
# This is crucial for large datasets to prevent browser crashes and improve performance
sampled_customerDensity_pdf = customerDensity.sample(False, 0.1, seed=42).toPandas()

# Create a folium map centered around Brazil's approximate center
m = folium.Map(location=[-14.235, -51.925], zoom_start=4)

# Add markers for each sampled point
for index, row in sampled_customerDensity_pdf.iterrows():
    if pd.notnull(row['geolocation_lat']) and pd.notnull(row['geolocation_lng']):
        folium.CircleMarker(
            location=[row['geolocation_lat'], row['geolocation_lng']],
            radius=1,
            color='blue',
            fill=True,
            fill_color='blue',
            fill_opacity=0.6,
            tooltip=f"Coordinate: {[row['geolocation_lat'], row['geolocation_lng']]}"
        ).add_to(m)

# Display the map
m

"""## Order Items EDA"""

items.show(5, truncate=False)

# Cek Null Values

items.select([
    count(when(
        col(c).isNull() |
        (isnan(col(c)) if isinstance(items.schema[c].dataType, (DoubleType, FloatType)) else False),
        c
    )).alias(c)
    for c in items.columns
]).show()

items.describe().show()

topOrders = items.groupBy('order_id').agg(
    F.sum('price').alias('price'),
    F.sum('freight_value').alias('freight_value')
)

topOrders = topOrders.withColumn('total_price', F.col('price') + F.col('freight_value'))

top10Orders = topOrders.orderBy(F.desc('total_price')).limit(10)
top10Orders.show()

# Konversi sampel data dari PySpark ke Pandas agar bisa dibaca oleh Seaborn
pdf_items_sample = items.select('price', 'freight_value').sample(False, 0.1, seed=42).toPandas()

# Boxplot untuk harga barang (price) dan ongkos kirim (freight_value)
fig, ax = plt.subplots(1, 2, figsize=(14, 5))

sns.boxplot(data=pdf_items_sample, x='price', ax=ax[0], color='skyblue')
ax[0].set_title('Distribusi Harga Barang (Price) - Cek Outlier')

sns.boxplot(data=pdf_items_sample, x='freight_value', ax=ax[1], color='salmon')
ax[1].set_title('Distribusi Ongkos Kirim (Freight Value) - Cek Outlier')

plt.tight_layout()
plt.show()

Q1 = pdf_items_sample['price'].quantile(0.25)
Q3 = pdf_items_sample['price'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = pdf_items_sample[
    (pdf_items_sample['price'] < lower) |
    (pdf_items_sample['price'] > upper)
]

print(f"Jumlah data outlier: {len(outliers)}")

Q1 = pdf_items_sample['freight_value'].quantile(0.25)
Q3 = pdf_items_sample['freight_value'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = pdf_items_sample[
    (pdf_items_sample['freight_value'] < lower) |
    (pdf_items_sample['freight_value'] > upper)
]

print(f"Jumlah data outlier: {len(outliers)}")

"""## Payments EDA"""

payments.show(5, truncate=False)

"""payment_value ini hasil penjumlahan price dan freight_value di table items"""

# Cek Null Values

payments.select([
    count(when(
        col(c).isNull() |
        (isnan(col(c)) if isinstance(payments.schema[c].dataType, (DoubleType, FloatType)) else False),
        c
    )).alias(c)
    for c in payments.columns
]).show()

payments.describe().show()

# Calculate value counts for payment_type
payment_counts = payments.groupBy('payment_type').count()

# Calculate total number of payments to get percentages
total_payments = payments.count()

# Calculate percentage and order by count in descending order
payment_distribution = payment_counts.withColumn(
    'percentage', (col('count') / total_payments) * 100
).orderBy(col('count').desc())

payment_distribution.show(truncate=False)

# Calculate value counts for payment_installments
payment_installments_counts = payments.groupBy('payment_installments').count()

# Calculate total number of payments to get percentages
total_payments = payments.count()

# Calculate percentage and order by count in descending order, then show top 10
payment_installments_distribution = payment_installments_counts.withColumn(
    'percentage', (col('count') / total_payments) * 100
).orderBy(col('count').desc()).limit(10)

payment_installments_distribution.show(truncate=False)

# Konversi sampel data dari PySpark ke Pandas agar bisa dibaca oleh Seaborn
pdf_payments_sample = payments.select('payment_value').sample(False, 0.1, seed=42).toPandas()

# Boxplot untuk payment_value
fig, ax = plt.subplots(1, figsize=(14, 5))

sns.boxplot(data=pdf_payments_sample, x='payment_value', ax=ax, color='skyblue')
ax.set_title('Distribusi Nilai Pembayaran (Payment Value) - Cek Outlier')

plt.tight_layout()
plt.show()

"""## Reviews EDA"""

reviews.show(5, truncate=False)

# Cek Null Values

reviews.select([
    count(when(
        col(c).isNull() |
        (isnan(col(c)) if isinstance(reviews.schema[c].dataType, (DoubleType, FloatType)) else False),
        c
    )).alias(c)
    for c in reviews.columns
]).show()

reviews = reviews.select("order_id", "review_score").dropna(subset=["review_score"])

# Calculate value counts for review_score
review_score_counts = reviews.groupBy('review_score').count()

# Calculate total number of reviews to get percentages
total_reviews = reviews.count()

# Calculate percentage and order by review_score
review_distribution = review_score_counts.withColumn(
    'percentage', (col('count') / total_reviews) * 100
).orderBy(col('review_score').asc())

review_distribution.show(truncate=False)

reviewScoreAnalysis = reviews.select('order_id', 'review_score').join(
    orders.select('order_id', 'purchased_approved', 'approved_carrier', 'carrier_delivered', 'delivered_estimated', 'purchased_delivered'),
    on='order_id',
    how='inner'
)
reviewScoreAnalysis.show(5)

columns_to_mean = ['review_score', 'purchased_approved', 'approved_carrier', 'carrier_delivered', 'delivered_estimated', 'purchased_delivered']

# Calculate mean for on-time deliveries
ontimeDelivery_review_pyspark = reviewScoreAnalysis.filter(F.col('delivered_estimated') > 0).agg(
    *[F.mean(col).alias(col) for col in columns_to_mean]
).collect()[0].asDict()

# Calculate mean for late deliveries
lateDelivery_review_pyspark = reviewScoreAnalysis.filter(F.col('delivered_estimated') < 0).agg(
    *[F.mean(col).alias(col) for col in columns_to_mean]
).collect()[0].asDict()

# Convert to pandas Series for comparison
ontimeDelivery_review = pd.Series(ontimeDelivery_review_pyspark)
lateDelivery_review = pd.Series(lateDelivery_review_pyspark)

comparison_review = pd.DataFrame([ontimeDelivery_review, lateDelivery_review]).T
comparison_review.rename(columns = {0 : 'on time delivery', 1 : 'late delivery'}, inplace = True)
comparison_review

from pyspark.sql.functions import col, when

# The partition logic: review_score < 3 becomes 'negative', 3 becomes 'neutral', and > 3 becomes 'positive'
# Assign the result of the transformation to a new DataFrame or overwrite the existing one.
reviewScoreAnalysis = reviews.withColumn(
    'review_score_partitioned',
    when(col('review_score') < 3, "negative")
    .when(col('review_score') == 3, "neutral")
    .otherwise("positive")
)

# checking the new partitioned review score distribution
reviewScoreAnalysis.groupBy('review_score_partitioned').count().show()

# Get the counts for positive (1) and negative (0) reviews from the partitioned review scores
review_counts_pdf = reviewScoreAnalysis.groupBy('review_score_partitioned').count().toPandas()

# Map the partition values to meaningful labels for three categories
review_counts_pdf['label'] = review_counts_pdf['review_score_partitioned'].map({
    'negative': 'Negative Reviews',
    'neutral': 'Neutral Reviews',
    'positive': 'Positive Reviews'
})

# Ensure the order for plotting is consistent (e.g., negative, neutral, positive)
# This might require sorting the DataFrame if the order is not guaranteed by groupBy
review_counts_pdf = review_counts_pdf.set_index('review_score_partitioned').loc[['negative', 'neutral', 'positive']].reset_index()


# Plotting the pie chart
plt.figure(figsize=(8, 8))
plt.pie(review_counts_pdf['count'],
        labels=review_counts_pdf['label'],
        autopct='%1.1f%%',
        startangle=90,
        colors=['#ff9999', '#ffcc99', '#A5CF83']) # Added a third color for neutral
plt.title('Perbandingan Ulasan (Negatif, Netral, Positif)') # Updated title
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

"""## Products EDA"""

products.show(5, truncate=False)

# Cek Null Values

products.select([
    count(when(
        col(c).isNull() |
        (isnan(col(c)) if isinstance(products.schema[c].dataType, (DoubleType, FloatType)) else False),
        c
    )).alias(c)
    for c in products.columns
]).show()

products = products.withColumn(
    "product_volume_cm3",
    F.col("product_length_cm") * F.col("product_height_cm") * F.col("product_width_cm")
)

orderedProducts = products.join(items, on='product_id', how='inner')
orderedProducts = orderedProducts.join(product_category_translation, on='product_category_name', how='inner')

orderedProducts = orderedProducts.select(
    col('product_id'),
    col('product_category_name_english'),
    col('product_name_lenght'),
    col('product_description_lenght'),
    col('product_photos_qty'),
    col('product_weight_g'),
    col('product_length_cm'),
    col('product_height_cm'),
    col('product_width_cm'),
    col('product_volume_cm3'),
    col('order_id'),
    col('price'),
    col('freight_value')
)

# Add the 'total_revenue' column
orderedProducts = orderedProducts.withColumn('total_revenue', col('price') + col('freight_value'))

# Display the head of the PySpark DataFrame
orderedProducts.show(5, truncate=False)

orderedProductsAnalysis = orderedProducts.groupBy('product_category_name_english').agg(
                                                        F.count('product_id').alias('product_count'),
                                                        F.count_distinct('order_id').alias('order_count'),
                                                        F.sum('price').alias('total_price'),
                                                        F.sum('freight_value').alias('total_freight_value'),
                                                        F.sum('total_revenue').alias('overall_total_revenue'))
orderedProductsAnalysis.show(5, truncate=False)

orderedProductsAnalysis.describe().show()

top10revenueGenerating_pdf = orderedProductsAnalysis.orderBy(F.desc('overall_total_revenue')).limit(10).toPandas()

fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(10, 7), sharey=True)
fig.suptitle('Analysis By Product Category', fontsize=20, fontweight = 'bold')

sns.barplot(ax=ax[0], x='overall_total_revenue', y= top10revenueGenerating_pdf.product_category_name_english, data = top10revenueGenerating_pdf)
ax[0].set_title('Revenue (in Millions)', fontsize = 15)
ax[0].set_ylabel('product category', fontsize = 15)

sns.barplot(ax=ax[1], x='order_count', y = top10revenueGenerating_pdf.product_category_name_english, data = top10revenueGenerating_pdf)
ax[1].set_title('No Of Orders', fontsize = 15)

for i in range(0,2):
    ax[i].set(xlabel=None)

for i in range(1,2):
    ax[i].set(ylabel=None)

plt.tight_layout()
plt.show()

"""# Gold Layer

## Merge All Dataframe
"""

from pyspark.sql.functions import broadcast
import pyspark.sql.functions as F

merged_df = customers_clean \
    .join(orders, on='customer_id', how='inner') \
    .join(items, on='order_id', how='inner') \
    .join(products, on='product_id', how='inner') \
    .join(broadcast(geolocationMean), customers_clean['customer_zip_code_prefix'] == geolocationMean['geolocation_zip_code_prefix'], how='inner') \
    .join(payments, on='order_id', how='inner') \
    .join(sellers, on='seller_id', how='inner') \
    .join(broadcast(product_category_translation), on='product_category_name', how='inner') \
    .join(reviews, on='order_id', how='left')

# PEMBUKTIAN DISTRIBUSI FREKUENSI PEMBELIAN
# Membuktikan bahwa ~97% pengguna adalah One-Time Buyer
# ==========================================
print("--- Pembuktian Distribusi One-Time Buyer ---")
# Hitung jumlah order unik per customer_unique_id
order_counts_df = merged_df.groupBy("customer_unique_id").agg(
    F.countDistinct("order_id").alias("total_orders")
).toPandas()
total_customers_count = len(order_counts_df)
one_time_buyers_count = (order_counts_df["total_orders"] == 1).sum()
repeat_buyers_count = (order_counts_df["total_orders"] > 1).sum()
print(f"Total Unique Customers: {total_customers_count}")
print(f"One-Time Buyers: {one_time_buyers_count} ({(one_time_buyers_count / total_customers_count) * 100:.2f}%)")
print(f"Repeat Buyers: {repeat_buyers_count} ({(repeat_buyers_count / total_customers_count) * 100:.2f}%)\n")
print("Rincian Distribusi Jumlah Order:")
print(order_counts_df["total_orders"].value_counts().sort_index().head(10))
print("\n")
# ==========================================

import matplotlib.pyplot as plt
import pandas as pd

# Assuming order_counts_df, total_customers_count, one_time_buyers_count, and repeat_buyers_count
# are already defined from the previous cell.

# Create a DataFrame for the pie chart
buyer_data = pd.DataFrame({
    'Buyer Type': ['One-Time Buyers', 'Repeat Buyers'],
    'Count': [one_time_buyers_count, repeat_buyers_count]
})

# Define colors for the pie chart
colors = ['#ff9999','#66b3ff']

# Create the pie chart
plt.figure(figsize=(8, 8))
plt.pie(
    buyer_data['Count'],
    labels=buyer_data['Buyer Type'],
    autopct=lambda p: '{:.2f}% ({:.0f})'.format(p, (p/100)*buyer_data['Count'].sum()), # Show percentage and count
    startangle=90,
    colors=colors,
    explode=(0.0, 0.1) # Explode the 'Repeat Buyers' slice for emphasis
)
plt.title('Persentase Distribusi One-Time vs. Repeat Buyers', fontweight='bold')
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

# ==========================================
# ANALISIS INTER-PURCHASE INTERVAL
# Justifikasi empiris untuk threshold churn
# ==========================================
# Hitung selisih hari antar-transaksi berurutan per pelanggan
customer_orders = merged_df.select(
    "customer_unique_id", "order_purchase_timestamp"
).distinct().orderBy("customer_unique_id", "order_purchase_timestamp")
w = Window.partitionBy("customer_unique_id").orderBy("order_purchase_timestamp")
customer_orders = customer_orders.withColumn(
    "prev_purchase", F.lag("order_purchase_timestamp").over(w)
)
customer_orders = customer_orders.withColumn(
    "days_between", F.datediff("order_purchase_timestamp", "prev_purchase")
).filter(F.col("days_between").isNotNull())
intervals_pd = customer_orders.select("days_between").toPandas()
# Hitung persentil
percentiles = [50, 75, 80, 85, 90, 95, 99]
print("--- Distribusi Selisih Hari Belanja (Repeat Buyers) ---")
for p in percentiles:
    val = np.percentile(intervals_pd["days_between"], p)
    print(f"P{p}: {val:.1f} hari")
# Visualisasi 1: Histogram distribusi
plt.figure(figsize=(10, 6))
sns.histplot(intervals_pd["days_between"], bins=50, kde=True, color='skyblue')
plt.axvline(x=180, color='red', linestyle='--', label='Proposed Churn Threshold (180 hari)')
plt.title("Distribusi Selisih Hari Antar Pembelian (Inter-Purchase Interval)")
plt.xlabel("Selisih Hari")
plt.ylabel("Jumlah Transaksi")
plt.legend()
plt.show()
# Visualisasi 2: CDF (Cumulative Distribution Function)
plt.figure(figsize=(10, 6))
sns.ecdfplot(intervals_pd["days_between"], color='green')
plt.axvline(x=180, color='red', linestyle='--', label='Proposed Churn Threshold (180 hari)')
plt.title("Cumulative Distribution Function (CDF) dari Inter-Purchase Interval")
plt.xlabel("Selisih Hari")
plt.ylabel("Proporsi Kumulatif")
plt.legend()
plt.show()

# Define cutoff date berdasarkan threshold empiris
# 180 hari itu berada di antara P80 (165 hari) dan P85 (200 hari)
# jarak waktu dari
# masih ada sisa waktu 6 hari untuk observasi (186-180)
CHURN_THRESHOLD_DAYS = 180
cutoff_date = "2018-03-01 00:00:00"

# Filter merged_df for observation window (features are constructed from these orders)
obs_df = merged_df.filter(F.col("order_purchase_timestamp") < cutoff_date)
# Get distinct customer_unique_ids who purchased in prediction window (on or after cutoff_date)
pred_df = merged_df.filter(F.col("order_purchase_timestamp") >= cutoff_date) \
    .select("customer_unique_id").distinct() \
    .withColumn("bought_in_pred_window", F.lit(1))

# 3. PEMBUATAN DATA MART & AGREGASI LEVEL PELANGGAN
data_mart = obs_df.groupBy("customer_unique_id").agg(
    F.max("customer_zip_code_prefix").alias("customer_zip_code_prefix"),
    F.max("customer_city").alias("customer_city"),
    F.max("customer_state").alias("customer_state"),
    F.countDistinct("order_id").alias("frequency"), # RFM: Frequency
    F.max("order_purchase_timestamp").alias("last_purchase_date"), # Untuk hitung Recency
    F.mean("purchased_approved").alias("purchased_approved"),
    F.mean("delivered_estimated").alias("delivered_estimated"),
    F.mean("purchased_delivered").alias("purchased_delivered"),
    F.countDistinct("product_id").alias("no_of_products"),
    F.sum("price").alias("price"),
    F.sum("freight_value").alias("freight_value"),
    F.mean("product_weight_g").alias("product_weight_g"),
    F.mean("product_volume_cm3").alias("product_volume_cm3"),
    F.mean("geolocation_lat").alias("geolocation_lat"),
    F.mean("geolocation_lng").alias("geolocation_lng"),
    F.expr("max_by(payment_type, payment_value)").alias("payment_type"),
    F.mean("payment_installments").alias("payment_installments"),
    F.sum("payment_value").alias("monetary"), # RFM: Monetary
    F.mean("review_score").alias("review_score"),
    F.max(F.when(F.col("order_status") == "canceled", 1).otherwise(0)).alias("has_canceled_order"),
    F.mean("order_item_id").alias("avg_items_per_order")
)

# 4. KALKULASI RECENCY
# Mengurangkan cutoff_date dengan last_purchase_date masing-masing pelanggan (untuk observation window)
data_mart = data_mart.withColumn(
    "recency",
    F.datediff(F.lit(cutoff_date), F.col("last_purchase_date"))
)

# Menangani nilai Recency 0 menjadi 1 (menghindari error log transform & asumsi hari yang sama)
data_mart = data_mart.withColumn(
    "recency",
    F.when(F.col("recency") == 0, 1).otherwise(F.col("recency"))
)

# Membuang kolom last_purchase_date karena sudah tidak dibutuhkan
data_mart = data_mart.drop("last_purchase_date")

# Labeling using prediction window (left join)
data_mart = data_mart.join(pred_df, on="customer_unique_id", how="left")

data_mart = data_mart.withColumn(
    "is_churn", F.when(F.col("bought_in_pred_window").isNull(), 1).otherwise(0)
)

data_mart = data_mart.drop("bought_in_pred_window")

# Tampilkan struktur akhir Data Mart
data_mart.orderBy("recency").show(5)

print(f"Rows: {data_mart.count()}, Columns: {len(data_mart.columns)}")

data_mart.printSchema()

"""## Cek Outlier

!!!HANDLING MISSING VALUE DAN OUTLIER SUDAH DIPINDAHKAN KE PIPELINE AGAR TIDAK TERJADI DATA LEAKAGE!!!
"""

data_mart_pd = data_mart.toPandas()

data_mart_pd['is_churn'] = data_mart_pd.is_churn.astype('object')

for col in data_mart_pd.select_dtypes(include = np.number).columns:
    plt.figure(figsize = (10, 5))
    print(f'Skewness of {col}: {data_mart_pd[col].skew()}')
    print(f'Standard deviation of {col}: {data_mart_pd[col].std()}')
    sns.boxplot(data_mart_pd[col])
    plt.title(f'Distribution of {col}')
    plt.show()

plt.show()

# Cek persentil recency saat ini di data mart
print("Recency di Data Mart:")
print(data_mart_pd["recency"].describe())

# Membuang kolom no_of_products karena nilai standar deviasinya hampir 0 (frequency dipertahankan!)
data_mart_pd.drop(columns = ['customer_zip_code_prefix', 'no_of_products'], axis = 1, inplace = True)

"""Tidak jadi kita drop karena Standard deviasi mendekati 0 karena ~97% pelanggan memang hanya punya 1 order ini justru informasi yang sangat penting! Pelanggan dengan frequency > 1 adalah repeat customer yang jauh lebih kecil kemungkinan churn-nya.

Fix: Jangan drop frequency. Sebaliknya, pertahankan sebagai fitur karena model tree-based (RF, XGBoost) sangat pandai memanfaatkan fitur yang "hampir konstan tapi punya outlier bermakna".
"""

data_mart_outlierTreated = data_mart_pd.copy()

# columns_to_cap = ['purchased_approved', 'delivered_estimated', 'purchased_delivered',
#                   'product_volume_cm3', 'monetary', 'payment_installments']
# for i in columns_to_cap:
#     if i in data_mart_outlierTreated.columns:
#         q1 = data_mart_outlierTreated[i].quantile(0.25)
#         q3 = data_mart_outlierTreated[i].quantile(0.75)
#         iqr = q3 - q1
#         ul = q3 + 1.5*iqr
#         ll = q1 - 1.5*iqr
#         data_mart_outlierTreated[i] = np.where(data_mart_outlierTreated[i]>ul,ul,data_mart_outlierTreated[i])
#         data_mart_outlierTreated[i] = np.where(data_mart_outlierTreated[i]<ll,ll,data_mart_outlierTreated[i])

# for col in data_mart_outlierTreated.select_dtypes(include = np.number).columns:
#     plt.figure(figsize = (10, 5))
#     print(f'Skewness of {col}: {data_mart_outlierTreated[col].skew()}')
#     print(f'Standard deviation of {col}: {data_mart_outlierTreated[col].std()}')
#     sns.boxplot(data_mart_outlierTreated[col])
#     plt.title(f'Distribution of {col}')
#     plt.show()

"""## Handling Missing Values"""

# Cek Null Values
data_mart_outlierTreated.isna().sum() / len(data_mart_pd) * 100

"""!!!HANDLING MISSING VALUE DAN OUTLIER SUDAH DIPINDAHKAN KE PIPELINE AGAR TIDAK TERJADI DATA LEAKAGE!!!"""

# # Imputasi review_score dan kolom numerik lainnya dengan median (JANGAN didrop!)
# for col_name in data_mart_outlierTreated.select_dtypes(include=np.number).columns:
#     if data_mart_outlierTreated[col_name].isna().any():
#         data_mart_outlierTreated[col_name] = data_mart_outlierTreated[col_name].fillna(data_mart_outlierTreated[col_name].median())

"""## Dashboard Visualizations (Churn Segmentation)"""

columns = ['recency', 'monetary', 'purchased_approved', 'delivered_estimated', 'purchased_delivered', 'product_volume_cm3', 'payment_installments']
# Fungsi encoding region
def get_region(state):
    if state in ['RS', 'SC', 'PR']: return 'Southern'
    elif state in ['SP', 'RJ', 'MG', 'ES']: return 'Southeastern'
    elif state in ['MT', 'MS', 'GO', 'DF']: return 'Centralwestern'
    elif state in ['MA', 'PI', 'CE', 'RN', 'PB', 'PE', 'AL', 'SE', 'BA']: return 'Northeastern'
    else: return 'Northern'
dashboard_df = data_mart_outlierTreated.copy()
# Pastikan is_churn bertipe numeric agar tidak error di Heatmap
dashboard_df['is_churn'] = dashboard_df['is_churn'].astype(int)
dashboard_df['is_churn_label'] = dashboard_df['is_churn'].apply(lambda x: "Churn" if x == 1 else "Active")
# 1. Churn Rate by Region
dashboard_df['region'] = dashboard_df['customer_state'].apply(get_region)
region_summary = dashboard_df.groupby('region')['is_churn'].agg(['mean', 'count']).reset_index()
region_summary.columns = ['Region', 'Churn Rate', 'Total Customers']
region_summary = region_summary.sort_values('Churn Rate', ascending=False)
fig, ax = plt.subplots(figsize=(10, 6))
bars = ax.bar(region_summary['Region'], region_summary['Churn Rate'] * 100, color='#e74c3c')
ax.set_ylabel('Churn Rate (%)')
ax.set_title('1. Churn Rate by Region')
for bar, count in zip(bars, region_summary['Total Customers']):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5, f'n={count:,}', ha='center', fontsize=9)
plt.tight_layout()
plt.show()
# 2. Churn Rate by Payment Type
pay_summary = dashboard_df.groupby('payment_type')['is_churn'].agg(['mean', 'count']).reset_index()
pay_summary.columns = ['Payment Type', 'Churn Rate', 'Total Customers']
pay_summary = pay_summary.sort_values('Churn Rate', ascending=False)
fig, ax = plt.subplots(figsize=(10, 6))
bars = ax.bar(pay_summary['Payment Type'], pay_summary['Churn Rate'] * 100, color='#3498db')
ax.set_ylabel('Churn Rate (%)')
ax.set_title('2. Churn Rate by Payment Type')
for bar, count in zip(bars, pay_summary['Total Customers']):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5, f'n={count:,}', ha='center', fontsize=9)
plt.tight_layout()
plt.show()
# 3. Review Score vs Churn
plt.figure(figsize=(10, 6))
sns.violinplot(data=dashboard_df, x='is_churn_label', y='review_score', hue='is_churn_label', palette='muted', legend=False)
plt.title('3. Distribution of Review Score (Churn vs Active)')
plt.xlabel('Status')
plt.ylabel('Average Review Score')
plt.tight_layout()
plt.show()
# 4. RFM Segmentation Heatmap (Recency vs Frequency)
dashboard_df['recency_bin'] = pd.qcut(dashboard_df['recency'], q=4, labels=['Q1 (Baru)', 'Q2', 'Q3', 'Q4 (Lama)'])
dashboard_df['frequency_bin'] = np.where(dashboard_df['frequency'] == 1, '1x', '>1x')
rf_pivot = dashboard_df.pivot_table(index='recency_bin', columns='frequency_bin', values='is_churn', aggfunc='mean') * 100
plt.figure(figsize=(8, 6))
sns.heatmap(rf_pivot, annot=True, fmt=".1f", cmap="YlOrRd", cbar_kws={'label': 'Churn Rate (%)'})
plt.title('4. Churn Rate Heatmap by Recency & Frequency')
plt.ylabel('Recency Quartile')
plt.xlabel('Frequency')
plt.tight_layout()
plt.show()
# 5. Monetary Distribution
plt.figure(figsize=(10, 6))
sns.kdeplot(data=dashboard_df, x='monetary', hue='is_churn_label', fill=True, common_norm=False, palette='muted')
plt.title('5. Monetary Value Distribution (Churn vs Active)')
plt.xlabel('Total Monetary Value')
plt.tight_layout()
plt.show()
# 6. Delivery Experience vs Churn
dashboard_df['delivery_status'] = np.where(dashboard_df['delivered_estimated'] < 0, 'Late', 'On-Time/Early')
del_summary = dashboard_df.groupby('delivery_status')['is_churn'].agg(['mean', 'count']).reset_index()
fig, ax = plt.subplots(figsize=(8, 6))
bars = ax.bar(del_summary['delivery_status'], del_summary['mean'] * 100, color=['#95a5a6', '#2ecc71'])
ax.set_ylabel('Churn Rate (%)')
ax.set_title('6. Churn Rate by Delivery Experience')
for bar, count in zip(bars, del_summary['count']):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5, f'n={count:,}', ha='center', fontsize=9)
plt.tight_layout()
plt.show()
del dashboard_df

"""## Target Variable Distribution (Imbalance Check)"""

data_mart_outlierTreated.is_churn.value_counts(normalize = True) * 100

import matplotlib.pyplot as plt
import seaborn as sns

# Atur ukuran kanvas
plt.figure(figsize=(8, 6))

# Buat countplot dengan palet warna yang kontras
ax = sns.countplot(
    data=data_mart_outlierTreated,
    x='is_churn',
    palette=['#66b3ff', '#ff9999'],
    hue='is_churn', # Ditambahkan agar tidak ada deprecation warning di Seaborn versi terbaru
    legend=False
)

# Hitung total data untuk kalkulasi persentase
total = len(data_mart_outlierTreated)

# Tambahkan anotasi (angka absolut + persentase) tepat di atas masing-masing bar
for p in ax.patches:
    count = int(p.get_height())
    percentage = f'{100 * count / total:.2f}%'
    x = p.get_x() + p.get_width() / 2
    y = p.get_height()

    # Anotasi angka ribuan dan persentasenya
    ax.annotate(f'{count:,}\n({percentage})',
                (x, y),
                ha='center',
                va='bottom',
                fontweight='bold',
                fontsize=12)

# Rapikan label dan judul
ax.set_xticklabels(['Non-Churn (0)', 'Churn (1)'])
plt.title('Distribusi Kelas Target: Imbalance Check', fontsize=15, fontweight='bold', pad=20)
plt.xlabel('Status Pelanggan', fontsize=12)
plt.ylabel('Jumlah Pelanggan', fontsize=12)

# Hilangkan garis tepi atas dan kanan agar lebih bersih
sns.despine()

plt.tight_layout()
plt.show()

"""## Correlation Matrix"""

import numpy as np

# Select only numeric columns for correlation matrix
# Exclude 'customer_unique_id', 'customer_city', 'customer_state', 'payment_type'
data_mart_outlierTreated['is_churn'] = data_mart_outlierTreated['is_churn'].astype(int)
numeric_cols = data_mart_outlierTreated.select_dtypes(include=np.number).columns.tolist()

# Filter out any remaining non-numeric columns from the selection that might be 'object' types but not intended for corr
# For example, customer_unique_id, customer_city, customer_state, payment_type are explicitly not numerical
# We will only proceed with columns that are currently numerical in the dataframe.

df_numeric_for_corr = data_mart_outlierTreated[numeric_cols]

plt.figure(figsize=(15,11))
sns.heatmap(df_numeric_for_corr.corr(), annot = True)
plt.title('Correlation Matrix of numerical variables',fontsize=20,fontweight='bold')
plt.show()

df_numeric_for_corr.describe()

plt.figure(figsize=(15,11))
sns.heatmap(df_numeric_for_corr.corr()[df_numeric_for_corr.corr() > 0.6], annot = True)
plt.title('Correlation Matrix of numerical variables',fontsize=20,fontweight='bold')
plt.show()

import numpy as np

# 1. Fitur volume sudah dihitung pada Silver & Gold Layer dengan PySpark.

# 2. Pembuatan fitur baru: freight_ratio (ongkir dibanding total pengeluaran)
# Menggunakan np.where untuk menghindari error ZeroDivision jika ada monetary yang bernilai 0
data_mart_outlierTreated["freight_ratio"] = np.where(
    data_mart_outlierTreated["monetary"] > 0,
    data_mart_outlierTreated["freight_value"] / data_mart_outlierTreated["monetary"],
    0
)

# 3. Proses Drop Kolom yang redundan
kolom_yang_didrop = [
    'price',
    'freight_value',
]

# Gunakan inplace=True tanpa menuliskan axis=1 lagi
data_mart_outlierTreated.drop(columns=kolom_yang_didrop, inplace=True)

numeric_cols = data_mart_outlierTreated.select_dtypes(include=np.number).columns.tolist()

df_numeric_for_corr = data_mart_outlierTreated[numeric_cols]

plt.figure(figsize=(15,11))
sns.heatmap(df_numeric_for_corr.corr(), annot = True)
plt.title('Correlation Matrix of numerical variables',fontsize=20,fontweight='bold')
plt.show()

data_mart_outlierTreated.info()

"""# Implementasi Machine Learning

## Encoding Features
"""

transformed_data = data_mart_outlierTreated.copy()
transformed_data['is_churn'] = transformed_data['is_churn'].astype('object')

transformed_data.describe()

transformed_data.head()

def state_encoding(state):
    if state in ['RS', 'SC', 'PR']:
        return 'southern'
    elif state in ['SP', 'RJ', 'MG', 'ES']:
        return 'southeastern'
    elif state in ['MT', 'MS', 'GO', 'DF']:
        return 'centralwestern'
    elif state in ['MA', 'PI', 'CE', 'RN', 'PB', 'PE', 'AL', 'SE', 'BA']:
        return 'northeastern'
    else:
        return 'northern'

transformed_data['customer_state'] = transformed_data['customer_state'].apply(state_encoding)

features = transformed_data.copy()
features.head()

features.drop(columns = ['customer_unique_id', 'customer_city'], axis = 1, inplace = True)

features.head(1)

independent = features.drop(columns = ['is_churn', 'recency'], errors='ignore')
df_numeric = independent.select_dtypes(include = np.number)
# pisahkan categorical dulu untuk dilakukan one-hot encoding
df_categorical = independent.select_dtypes(exclude = np.number)
y = features['is_churn'].astype(int)

encoded_data = pd.get_dummies(df_categorical, drop_first = True)
# drop first digunakan untuk mendrop salah satu variable agar tidak redundan

# menggabungkan numeric dan categorical yang sudah di encoding
X = pd.concat([df_numeric, encoded_data], axis = 1)

X.info()

"""## Prepare Training Model"""

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn import set_config
import numpy as np

# Memaksa Scikit-Learn agar output berbentuk DataFrame (menjaga nama kolom)
set_config(transform_output="pandas")

class IQROutlierCapper(BaseEstimator, TransformerMixin):
    def __init__(self, columns_to_cap):
        self.columns_to_cap = columns_to_cap
        self.limits_ = {}

    def fit(self, X, y=None):
        # Menghitung batas IQR HANYA dari data yang di-fit (data training)
        for col in self.columns_to_cap:
            if col in X.columns:
                q1 = X[col].quantile(0.25)
                q3 = X[col].quantile(0.75)
                iqr = q3 - q1
                self.limits_[col] = {
                    'lower': q1 - 1.5 * iqr,
                    'upper': q3 + 1.5 * iqr
                }
        return self

    def transform(self, X, y=None):
        # Menerapkan capping berdasarkan batas yang sudah dipelajari
        X_transformed = X.copy()
        for col in self.columns_to_cap:
            if col in X_transformed.columns and col in self.limits_:
                upper_limit = self.limits_[col]['upper']
                lower_limit = self.limits_[col]['lower']
                X_transformed[col] = np.where(X_transformed[col] > upper_limit, upper_limit, X_transformed[col])
                X_transformed[col] = np.where(X_transformed[col] < lower_limit, lower_limit, X_transformed[col])
        return X_transformed

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from imblearn.pipeline import Pipeline as ImblearnPipeline

columns_to_cap = ['purchased_approved', 'delivered_estimated', 'purchased_delivered',
                  'product_volume_cm3', 'monetary', 'payment_installments']

# Pipeline preprocessing terisolasi
preprocessing_pipeline = ImblearnPipeline([
    ('capper', IQROutlierCapper(columns_to_cap=columns_to_cap)),
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# 1. Install Library yang dibutuhkan (jika belum ada)
try:
    import xgboost
    import shap
except ImportError:
    os.system(f'{sys.executable} -m pip install xgboost scikit-learn shap -q')

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

import pandas as pd
import numpy as np
import xgboost as xgb
from imblearn.over_sampling import SMOTE
from sklearn.pipeline import Pipeline
from imblearn.pipeline import Pipeline as ImblearnPipeline
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)

import matplotlib.pyplot as plt
import seaborn as sns

# 4. Split Data (80% Training, 20% Testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
print(f"Jumlah data training: {len(X_train)}")
print(f"Jumlah data testing: {len(X_test)}")

# 5. Fit dan transform preprocessing (Capper, Imputer, Scaler)
X_train_scaled = preprocessing_pipeline.fit_transform(X_train)
X_test_scaled = preprocessing_pipeline.transform(X_test)

# =========================================================
# 6. PERBAIKAN: TERAPKAN RANDOM UNDER-SAMPLING PADA DATA TRAINING
# =========================================================
from imblearn.under_sampling import RandomUnderSampler

rus = RandomUnderSampler(sampling_strategy='auto', random_state=42)

# Resample hanya data training! Data testing dibiarkan apa adanya.
X_train_resampled, y_train_resampled = rus.fit_resample(X_train_scaled, y_train)

print(f"\nDistribusi y_train SEBELUM RUS:\n{y_train.value_counts()}")
print(f"Distribusi y_train SETELAH RUS:\n{y_train_resampled.value_counts()}")

"""## Latih Model Logistic Regression"""

# =========================
# LOGISTIC REGRESSION
# =========================

lr_model = LogisticRegression(max_iter=2000, random_state=42) # Hapus class_weight='balanced'
lr_model.fit(X_train_resampled, y_train_resampled)

y_pred_lr = lr_model.predict(X_test_scaled)
y_prob_lr = lr_model.predict_proba(X_test_scaled)[:, 1]

print("=== Logistic Regression ===")
print(classification_report(y_test, y_pred_lr))

lr_accuracy = accuracy_score(y_test, y_pred_lr)
lr_precision = precision_score(y_test, y_pred_lr, average='macro')
lr_recall = recall_score(y_test, y_pred_lr, average='macro')
lr_f1 = f1_score(y_test, y_pred_lr, average='macro')
lr_auc = roc_auc_score(y_test, y_prob_lr)

"""## Latih Model Random Forest"""

# =========================
# RANDOM FOREST
# =========================

rf_model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42, n_jobs=-1) # Hapus class_weight
rf_model.fit(X_train_resampled, y_train_resampled)

y_pred_rf = rf_model.predict(X_test_scaled)
y_prob_rf = rf_model.predict_proba(X_test_scaled)[:, 1]

rf_accuracy = accuracy_score(y_test, y_pred_rf)
rf_precision = precision_score(y_test, y_pred_rf, average='macro')
rf_recall = recall_score(y_test, y_pred_rf, average='macro')
rf_f1 = f1_score(y_test, y_pred_rf, average='macro')
rf_auc = roc_auc_score(y_test, y_prob_rf)

"""## Latih Model XGBoost"""

xgb_model = xgb.XGBClassifier(
    objective='binary:logistic',
    eval_metric='auc',
    random_state=42,
    max_depth=5,
    learning_rate=0.1,
    n_estimators=100
) # scale_pos_weight sudah Anda hapus sebelumnya, biarkan terhapus.
xgb_model.fit(X_train_resampled, y_train_resampled)

# 8. Prediksi pada data Test
y_pred_xgb = xgb_model.predict(X_test_scaled)
y_prob_xgb = xgb_model.predict_proba(X_test_scaled)[:, 1]

xgb_accuracy = accuracy_score(y_test, y_pred_xgb)
xgb_precision = precision_score(y_test, y_pred_xgb, average='macro')
xgb_recall = recall_score(y_test, y_pred_xgb, average='macro')
xgb_f1 = f1_score(y_test, y_pred_xgb, average='macro')
xgb_auc = roc_auc_score(y_test, y_prob_xgb)

# =========================
# MODEL COMPARISON
# =========================

comparison_df = pd.DataFrame({
    'Model': [
        'Logistic Regression',
        'Random Forest',
        'XGBoost',
    ],
    'Accuracy': [
        lr_accuracy,
        rf_accuracy,
        xgb_accuracy,
    ],
    'Precision': [
        lr_precision,
        rf_precision,
        xgb_precision,
    ],
    'Recall': [
        lr_recall,
        rf_recall,
        xgb_recall,
    ],
    'F1-Score': [
        lr_f1,
        rf_f1,
        xgb_f1,
    ],
    'ROC-AUC': [
        lr_auc,
        rf_auc,
        xgb_auc,
    ]
})

comparison_df

from sklearn.metrics import classification_report

# =========================
# CLASSIFICATION REPORTS
# =========================

print("=" * 60)
print("LOGISTIC REGRESSION")
print("=" * 60)
print(classification_report(y_test, y_pred_lr))

print("\n")

print("=" * 60)
print("RANDOM FOREST")
print("=" * 60)
print(classification_report(y_test, y_pred_rf))

print("\n")

print("=" * 60)
print("XGBOOST")
print("=" * 60)
print(classification_report(y_test, y_pred_xgb))

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix

# =========================
# CONFUSION MATRIX FUNCTION
# =========================

def plot_conf_matrix(y_true, y_pred, title, ax):

    cm = confusion_matrix(y_true, y_pred)

    disp = ConfusionMatrixDisplay(
        confusion_matrix=cm,
        display_labels=["Not Churn", "Churn"]
    )

    disp.plot(ax=ax)

    ax.set_title(title)
    ax.grid(False)

# =========================
# PLOT ALL
# =========================

fig, axes = plt.subplots(1, 3, figsize=(15, 5)) # 1 row, 3 columns

plot_conf_matrix(
    y_test,
    y_pred_lr,
    "Logistic Regression Confusion Matrix",
    axes[0]
)

plot_conf_matrix(
    y_test,
    y_pred_rf,
    "Random Forest Confusion Matrix",
    axes[1]
)

plot_conf_matrix(
    y_test,
    y_pred_xgb,
    "XGBoost Confusion Matrix",
    axes[2]
)

plt.tight_layout()
plt.show()

"""## ROC Curve"""

from sklearn.metrics import roc_curve

# =========================
# ROC CURVE
# =========================

fpr_lr, tpr_lr, _ = roc_curve(y_test, y_prob_lr)
fpr_rf, tpr_rf, _ = roc_curve(y_test, y_prob_rf)
fpr_xgb, tpr_xgb, _ = roc_curve(y_test, y_prob_xgb)

plt.figure(figsize=(8,6))

plt.plot(fpr_lr, tpr_lr,
         label=f'Logistic Regression (AUC = {lr_auc:.3f})')

plt.plot(fpr_rf, tpr_rf,
         label=f'Random Forest (AUC = {rf_auc:.3f})')

plt.plot(fpr_xgb, tpr_xgb,
         label=f'XGBoost (AUC = {xgb_auc:.3f})')

plt.plot([0,1], [0,1], linestyle='--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison")

plt.legend()
plt.grid(True)

plt.show()

# PRECISION-RECALL CURVE COMPARISON
# ==========================================
from sklearn.metrics import precision_recall_curve, average_precision_score
plt.figure(figsize=(8,6))
for name, y_prob in [("Logistic Regression", y_prob_lr),
                     ("Random Forest", y_prob_rf),
                     ("XGBoost", y_prob_xgb)]:
    precision, recall, _ = precision_recall_curve(y_test, y_prob)
    ap = average_precision_score(y_test, y_prob)
    plt.plot(recall, precision, label=f'{name} (AP = {ap:.3f})')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve Comparison')
plt.legend()
plt.grid(True)
plt.show()
# ==========================================

# ==========================================
# FEATURE IMPORTANCE (INTERPRETASI BISNIS)
# ==========================================

# GANTI KODE YANG INI:
feature_importances = xgb_model.feature_importances_
feature_names = X.columns # Menggunakan nama baru agar tidak menimpa DataFrame 'features'

df_importance = pd.DataFrame({
    'Feature': feature_names,
    'Importance': feature_importances
})

# Urutkan agar feature terpenting tampil di atas
df_importance = df_importance.sort_values(
    by='Importance',
    ascending=False
)

# Visualisasi
plt.figure(figsize=(10, 6))

sns.barplot(
    data=df_importance,
    x='Importance',
    y='Feature',
    palette='viridis',
    hue='Importance',
    legend=False
)

plt.title('XGBoost Feature Importance untuk Prediksi Churn')
plt.xlabel('Tingkat Kepentingan')
plt.ylabel('Fitur')

plt.tight_layout()
plt.show()

"""## Evaluasi Menggunakan K-Fold"""

# 1. Definisikan Stratified K-Fold (misalnya 5 lipatan/folds)
# shuffle=True penting untuk mengacak data sebelum dibagi
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# 2. Definisikan metrik yang ingin dievaluasi (sesuai standar scikit-learn)
scoring_metrics = ['accuracy', 'precision_macro', 'recall_macro', 'f1_macro', 'roc_auc']

# 3. Fungsi pembantu untuk melakukan cross-validation dan mengambil rata-ratanya
def evaluate_model_kfold(model, X, y, cv, scoring):
    # Lakukan K-Fold Cross Validation (n_jobs=-1 agar menggunakan semua core CPU/lebih cepat)
    cv_results = cross_validate(model, X, y, cv=cv, scoring=scoring, n_jobs=-1)

    # Ambil rata-rata (mean) dari hasil 5 folds untuk masing-masing metrik
    mean_results = {
        'Accuracy': np.mean(cv_results['test_accuracy']),
        'Precision': np.mean(cv_results['test_precision_macro']),
        'Recall': np.mean(cv_results['test_recall_macro']),
        'F1-Score': np.mean(cv_results['test_f1_macro']),
        'ROC-AUC': np.mean(cv_results['test_roc_auc'])
    }
    return mean_results

print("Sedang memproses 5-Fold Cross Validation. Mohon tunggu...\n")

# 4. Jalankan evaluasi dengan memetakan steps secara mendatar (flat) tanpa nested pipeline

# 1. Logistic Regression
lr_kfold_results = evaluate_model_kfold(
    ImblearnPipeline([
        ('capper', IQROutlierCapper(columns_to_cap=columns_to_cap)),
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler()),
        ('under_sampler', RandomUnderSampler(sampling_strategy='auto', random_state=42)),
        ('lr', LogisticRegression(max_iter=2000, random_state=42))
    ]), X, y, skf, scoring_metrics
)

# 2. Random Forest
rf_kfold_results = evaluate_model_kfold(
    ImblearnPipeline([
        ('capper', IQROutlierCapper(columns_to_cap=columns_to_cap)),
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler()),
        ('under_sampler', RandomUnderSampler(sampling_strategy='auto', random_state=42)),
        ('rf', RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42, n_jobs=-1))
    ]), X, y, skf, scoring_metrics
)

# 3. XGBoost
xgb_kfold_results = evaluate_model_kfold(
    ImblearnPipeline([
        ('capper', IQROutlierCapper(columns_to_cap=columns_to_cap)),
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler()),
        ('under_sampler', RandomUnderSampler(sampling_strategy='auto', random_state=42)),
        ('xgb', xgb.XGBClassifier(objective='binary:logistic', eval_metric='auc', random_state=42, max_depth=5, learning_rate=0.1, n_estimators=100))
    ]), X, y, skf, scoring_metrics
)

# 4. Gabungkan hasil ke dalam satu DataFrame untuk perbandingan
kfold_comparison_df = pd.DataFrame([
    {'Model': 'Logistic Regression', **lr_kfold_results},
    {'Model': 'Random Forest', **rf_kfold_results},
    {'Model': 'XGBoost', **xgb_kfold_results},
])

print("=== Rata-Rata Kinerja Model Setelah Perbaikan Perimbangan Data ===")
try:
    display(kfold_comparison_df)
except NameError:
    print(kfold_comparison_df.to_string())

import shap
import numpy as np
import matplotlib.pyplot as plt

try:
    print("\nMenghitung SHAP values untuk Logistic Regression. Ini mungkin memakan waktu beberapa menit...")

    # Buat SHAP explainer untuk Logistic Regression
    # Gunakan LinearExplainer untuk model linear seperti Logistic Regression
    # Memerlukan background dataset (biasanya data training) untuk menghitung ekspektasi SHAP values
    explainer_lr = shap.LinearExplainer(lr_model, X_train_scaled)

    # Ambil sample dari data test yang SUDAH DI-SCALE
    # Menggunakan X_test_scaled yang sudah ada
    X_test_shap_lr = X_test_scaled.sample(n=min(5000, len(X_test_scaled)), random_state=42)

    # Hitung SHAP values
    shap_values_lr = explainer_lr.shap_values(X_test_shap_lr)

    # 1. SHAP Summary Plot (Beeswarm)
    plt.figure(figsize=(12, 8))
    shap.summary_plot(shap_values_lr, X_test_shap_lr, show=False)
    plt.title("SHAP Summary Plot - Logistic Regression (Dampak Fitur Terhadap Churn)")
    plt.tight_layout()
    plt.show()

    # 2. SHAP Bar Plot (Global Feature Importance)
    plt.figure(figsize=(8, 12))
    shap.summary_plot(shap_values_lr, X_test_shap_lr, plot_type="bar", show=False)
    plt.title("SHAP Global Feature Importance - Logistic Regression (Rata-rata Dampak Absolut)")
    plt.tight_layout()
    plt.show()

    # 3. SHAP Dependence Plot untuk 2 fitur teratas
    # Cari 2 fitur dengan rata-rata SHAP absolut tertinggi
    mean_abs_shap_lr = np.abs(shap_values_lr).mean(axis=0)
    top_indices_lr = np.argsort(mean_abs_shap_lr)[::-1][:2]
    top_features_shap_lr = X_test_shap_lr.columns[top_indices_lr]

    for feat in top_features_shap_lr:
        shap.dependence_plot(feat, shap_values_lr, X_test_shap_lr, show=False)
        plt.title(f"SHAP Dependence: {feat} (Logistic Regression)")
        plt.tight_layout()
        plt.show()

except Exception as e:
    print(f"Error saat membuat plot SHAP untuk Logistic Regression: {e}")
    print("Pastikan library 'shap' sudah terinstall (pip install shap) dan model Logistic Regression sudah dilatih.")

# --- Original XGBoost SHAP Analysis (kept for reference or if the user wants to re-run it) ---
"""## SHAP Analysis (Model Interpretability)"""
# ==========================================
# SHAP ANALYSIS
# Menginterpretasikan model XGBoost
# ==========================================
try:
    print("\nMenghitung SHAP values untuk XGBoost. Ini mungkin memakan waktu beberapa menit...")

    # Buat SHAP explainer untuk XGBoost
    explainer_xgb = shap.TreeExplainer(xgb_model)

    # Ambil sample dari data test yang SUDAH DI-SCALE DAN DI-IMPUTE
    X_test_shap_xgb = X_test_scaled.sample(n=min(5000, len(X_test_scaled)), random_state=42)

    shap_values_xgb = explainer_xgb.shap_values(X_test_shap_xgb)
    # 1. SHAP Summary Plot (Beeswarm)
    plt.figure(figsize=(12, 8))
    shap.summary_plot(shap_values_xgb, X_test_shap_xgb, show=False)
    plt.title("SHAP Summary Plot - XGBoost (Dampak Fitur Terhadap Churn)")
    plt.tight_layout()
    plt.show()
    # 2. SHAP Bar Plot (Global Feature Importance)
    plt.figure(figsize=(8, 12))
    shap.summary_plot(shap_values_xgb, X_test_shap_xgb, plot_type="bar", show=False)
    plt.title("SHAP Global Feature Importance (Rata-rata Dampak Absolut)")
    plt.tight_layout()
    plt.show()
    # 3. SHAP Dependence Plot untuk 2 fitur teratas
    # Cari 2 fitur dengan rata-rata SHAP absolut tertinggi
    mean_abs_shap_xgb = np.abs(shap_values_xgb).mean(axis=0)
    top_indices_xgb = np.argsort(mean_abs_shap_xgb)[::-1][:2]
    top_features_shap_xgb = X_test_shap_xgb.columns[top_indices_xgb]
    for feat in top_features_shap_xgb:
        shap.dependence_plot(feat, shap_values_xgb, X_test_shap_xgb, show=False)
        plt.title(f"SHAP Dependence: {feat} (XGBoost)")
        plt.tight_layout()
        plt.show()

except Exception as e:
    print(f"Error saat membuat plot SHAP untuk XGBoost: {e}")
    print("Pastikan library 'shap' sudah terinstall (pip install shap)")