name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # Memungkinkan trigger manual dari GitHub Actions UI
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Bikin identitas git sementara
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Simpan hash commit saat ini
          COMMIT_SHA=$(git rev-parse HEAD)
          
          # Bikin branch baru yang 100% KOSONG dan nggak bawa "dosa" history masa lalu
          git checkout --orphan hf-deploy
          
          # Hapus semua file bawaan dari index dan hapus bersih working directory
          git rm -rf .
          
          # CUMA ambil 4 file ini yang penting untuk Hugging Face
          git checkout $COMMIT_SHA -- app.py requirements.txt logreg_pipeline_olist.pkl README.md
          
          # Commit file-file bersih tersebut
          git commit -m "Deploy to HF without large histories"
          
          # Push force ke Hugging Face
          git push --force https://ardavv:$HF_TOKEN@huggingface.co/spaces/ardavv/churn-prediction-olist hf-deploy:main
